### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by eraclitux** [marinho/geraldo#32]
Hi, got this:

```
Traceback (most recent call last):
  File "/opt/easycloud_django/easypanel/views.py", line 882, in adminServerReportCsv
    report_server.generate_by(CSVGenerator, filename=resp)
  File "/opt/easycloud_env/lib/python2.6/site-packages/geraldo/base.py", line 435, in generate_by
    return generator.execute()
  File "/opt/easycloud_env/lib/python2.6/site-packages/geraldo/generators/csvgen.py", line 66, in execute
    self.generate_csv()
  File "/opt/easycloud_env/lib/python2.6/site-packages/geraldo/generators/csvgen.py", line 119, in generate_csv
    self.writer.writerow(cells)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 3: ordinal not in range(128)
```

When subclassing:

``` python
class myBandDetail(DetailBand):
                elements = [
                    ObjectValue(expression='user.username'),
                    ObjectValue(expression='user.first_name'),
                    ObjectValue(expression='user.last_name'),
                    ObjectValue(expression='name'),
                    ObjectValue(expression='plan.name'),
                    ObjectValue(attribute_name='creation_date',
                                get_value=lambda instance: instance.creation_date.strftime('%d/%m/%Y %H:%M')),
                    ObjectValue(attribute_name='deletion_date',
                                get_value=lambda instance: instance.deletion_date.strftime('%d/%m/%Y %H:%M') if instance.deletion_date else '',
                    ),
                    ObjectValue(expression='month_billing',
                                get_value=lambda instance: ('%.2f' % instance.month_billing).replace('.',','),
                    ),
                ]
```

where `user.last_name` contains "è" or other non-ascii char

**Comment by fvlima** [comment]
I had the same problem, and I have created my own CSVGenerator inheriting from the orginal, and overriding the method generate_csv to force self.writer.writerow([cell.encode('utf-8') for cell in cells]). This solved my problem.
